---
title: "PSTAT 131 Final Project Data Memo"
author: "Harrison Hansen"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---


```{r setup, echo=FALSE, include = FALSE}

# set global chunk options: images will be 7x5 inches

knitr::opts_chunk$set(fig.width=7, fig.height=5)
options(digits = 4)

## indents are for indenting r code as formatted text
## They may need to be adjusted depending on your OS
# if your output looks odd, increase or decrease indent

indent1 = '    '
indent2 = '        '
indent3 = '            '
```

### Dataset Overview

My chosen dataset is the voting distribution of Baseball Cy Young candidates. It
includes the final outcome of the voting, via a point system, along with the major
sabermetric statistics that measure a pitcher's performance throughout the year.
I will obtaining the dataset from
[Baseball Reference](https://www.baseball-reference.com/awards/awards_2021.shtml#AL_CYA_voting_link).
It allows downloading a csv file for each year's candidates, I will have to combine them
into one data matrix. This site also has more pitching data which I can add as 
additional predictor variables. The amount of observations is dependent on the
year I begin collecting voting data from, this could range from the 1960s to the
early 2000s. As we get closer to modern day, the statistics used to quantify a 
pitcher's performance has gotten more advanced, so the earlier voting data
may not be relevant today. The amount of predictors is also variable, as I can
add as many as I see fit. The type of predictor variables I will be working with 
will be entirely quantitative. The response variable will most likely be 
quantitative as well. I could either make the response quantitative for how many
points each pitcher will receive, or simply make it categorical, as yes/no for
the winner. There is no missing data from what I have seen, but if I do come upon
any I can simply replace that variable with another, since there are an endless 
number of pitching statistics to choose from.


### Overview of your Research Question(s)?

The variables I am interested in predicting would be the total number of points
a cy young candidate will receive based on numerous pitching statistics, which
will be the predictor variables. The questions I am interested in answering are
whether it is possible to predict the cy young winner? And is it possible to predict
the overall voting distribution for cy young candidates? I think the questions
will best be answered from a regression approach, as comparing a quantitative score
is definitive, but a classification approach could also work if I just focus on
whether a player wins/loses. The predictors I think will be especially useful
are the statistics that compares pitching performance (as judged by ERA) 
to the league average. These are designated with a "+" symbol, and provide an 
easy method of comparing pitchers from different eras, since they will be compared
to the league from when they played. The goal of my model is inferential, as I am
interested in understanding the association between Y, the amount of points a cy young
candidate receives, and $X_1,...,X_p$, the pitcher's numerous statistics. My goal
is to find which pitching statistics are associated with voting points, the relationship
between the voting points and each statistic, and whether the relationship between
voting points and each pitching statistic can be summarized using a linear or
non-linear equation.


### Proposed Project Timeline

I plan on having my dataset loaded by the end of next week. By the end of October, 
I will perform and document my exploratory data analysis as well as write 
an introduction to the project. During November, I will focus on setting up models,
model building, results of models, and visualizing performance. Each Sunday I 
will like to have made significant progress to not fall behind.

### Questions/Concerns

Which question do you think would be simpler/more interesting to answer?

Is it possible to predict the Cy Young winner? 

Or

Is it possible to predict the overall voting distribution of Cy Young candidates?

How many predictor variables is ideal? I can have anywhere between 20-50+.




